---
- name: Register a variable with a loop
  hosts: localhost
  tasks:
    - name: Run some commands on the host
      command: "{{ item }}"
      loop:
        - echo "Loop Message 1"
        - echo "Loop Message 2"
        - echo "Loop Message 3"
      register: output

    - name: Print out the data in output
      debug:
        msg: "{{ output }}"
      loop: "{{ output.results }}"
